
CREATE TABLE USER (
	id INT(20) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(150) NOT NULL,
	RandomString VARCHAR(100) UNIQUE NOT NULL,
	post VARCHAR(20) NOT NULL,
	system VARCHAR(50) NOT NULL,
	last_login DATE,
	is_superuser BOOL,
	email VARCHAR(50)
);
SELECT * FROM USER;