CREATE TABLE USER2 (
	id INT(20) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	post VARCHAR(20)UNIQUE NOT NULL,
	system VARCHAR(50)UNIQUE NOT NULL
);
SELECT * FROM USER2;
DESC user2;
ALTER TABLE user2 ADD FOREIGN KEY user2(post) REFERENCES post(post);
